general:
  root_path: ${CONFIG_PATH}
  csv_name:  instances.csv
  complete_verifier: bab
  save_adv_example: true
model:
  onnx_path: ${CONFIG_PATH}/model.onnx
  onnx_optimization_flags: ["merge_bn"]
attack:
  pgd_order: middle
  pgd_restarts: 100
solver:
  auto_enlarge_batch_size: True
  batch_size: 256
  beta-crown:
    lr_alpha: 0.1
    lr_beta: 0.2
    iteration: 10
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
    full_conv_alpha: False
bab:
  initial_max_domains: 2
  interm_transfer: False
  timeout: 100
  branching:
    method: kfsb
    candidates: 7
    reduceop: max